### ISSUE TITLE
Setup of IAQ sensors

### ISSUE THREAD

**Issue by manuelbrgr** [manuelbrgr/indoor-air-monitor#1]
### Description:
The sensors are connected to the Raspberry Pi and are able to collect accurate data. Some sensors, such as the CO2 sensor, need to be calibrated in order to make accurate measurements.

### Tasks:
- [x] Temperature sensor
- [x] Humidity sensor
- [x] Air pressure sensor
- [x] Gas sensor (REDd, OX and NH3)
- [x] CO2 sensor
- [x] VOC sensor (TVOC, eCO2)
- [x] Particulate matter sensor (PM1, PM2.5, PM10)
- [x] Window sensor (or balcony door)
- [x] Radiator thermostat sensor
- [x] Outdoor weather data from an external service

### Acceptance Criteria:
- [x] A python script for reading each sensor is added to the repository
- [x] The Raspberry Pi can connect to all sensors upon request
