### ISSUE TITLE
Implement data-collection of sensor data

### ISSUE THREAD

**Issue by manuelbrgr** [manuelbrgr/indoor-air-monitor#2]
### Description:
The data of IAQ sensors is collected periodically (e.g. every 30 seconds) and stored in a local CSV file. Regularly the file is synced into an AWS S3 bucket. Despite that, the currently collected is sent on every measurement to AWS IoT Core.

### Tasks:
- [ ] Implement script to collect sensor data into CSV file
- [ ] Add script to automatically start after bootup
- [ ] Setup periodical sync to AWS S3
- [ ] Setup sync with AWS IoT Core

### Acceptance Criteria:
- [ ] The sensor data is collected into a CSV file
- [ ] The CSV file is periodically synced with AWS S3
- [ ] The sensor data is synced with AWS IoT Core
