### ISSUE TITLE
Setup basic dashboard for showing sensor data

### ISSUE THREAD

**Issue by manuelbrgr** [manuelbrgr/indoor-air-monitor#3]
### Description:
A basic web application reachable via a public URL should show the live sensor data from AWS IoT Core. The page itself should be password protected.

### Tasks:
- [x] Register domain
- [x] Setup basic web dashboard with dummy data
- [x] Setup API for sensor data
- [x] Integrate API with web dashboard

### Acceptance Criteria:
- [x] The web application shows a dashboard with the current sensor data
